import 'package:hyper_split_bill/features/bill_splitting/domain/entities/participant_entity.dart';

// Data Transfer Object (DTO) or Model for Participant data.
class ParticipantModel extends ParticipantEntity {
  const ParticipantModel({
    super.id, // ID might be null when creating
    required super.name,
    super.linkedProfileId,
  });

  factory ParticipantModel.fromEntity(ParticipantEntity entity) {
    return ParticipantModel(
      id: entity.id,
      name: entity.name,
      linkedProfileId: entity.linkedProfileId,
    );
  }

  factory ParticipantModel.fromMap(Map<String, dynamic> map) {
    if (map['name'] == null) {
      throw ArgumentError(
          'Missing required field "name" in ParticipantModel.fromMap: $map');
    }
    return ParticipantModel(
      id: map['id'] as String?, // ID from DB
      name: map['name'] as String,
      linkedProfileId: map['linked_profile_id'] as String?,
    );
  }

  Map<String, dynamic> toMap({required String billId}) {
    // Dòng mới: chỉ cần billId
    return {
      // 'id' is excluded on insert, generated by DB
      'bill_id': billId,
      // 'user_id': userId, // Xóa dòng này
      'name': name,
      'linked_profile_id': linkedProfileId,
    };
  }
}
